# Use with mkdocs documentation generator https://www.mkdocs.org/
# docs.md => docs
# To build run:
# mkdocs build

site_name: STM32GENERIC
docs_dir: docs.md
site_dir: docs
pages:
- Installation: README.md
- Uploading: upload.md
- Documentation:
    - Menu options: menu_options.md
    - Arduino API: arduino_api.md
    - SPI: spi.md
    - I2C: i2c.md
    - I2S: i2s.md
    - SDIO: sdio.md
    - UART Serial: uart.md
    - USB Serial: usb_cdc.md
    - USB Mass Storage: usb_msc.md
    - STM32 HAL: stm32_hal.md
    - Build macros: build_macros.md
- Libraries: libraries.md
- STM32 Boards:
    - MapleMini F103CB: board_MapleMini_F103CB.md
    - BluePill F103CB: board_BluePill.md
    - Generic F103RF: board_Generic103RF.md
    - huaweiwx F103Z boards:
        - RedBull(F103ZE): board_F103ZE1.md
        - GENERIC(STM32F103ZE): board_F103ZE.md
        - GENERIC(STM32F103ZF): board_F103ZF.md
        - GENERIC(STM32F103ZG): board_F103ZG.md
    - BLUE F103VE/ZE/ZG boards:
        - BLUE F103VE vcc-gnd.com: board_BLUE_F103VE.md
        - BLUE F103ZE vcc-gnd.com: board_BLUE_F103ZE.md
        - BLUE F103ZG vcc-gnd.com: board_BLUE_F103ZG.md
    - BLACK F407VE/ZE/ZG boards:
        - BLACK F407VE (V2.0): board_BLACK_F407VE.md
        - BLACK F407ZE (V3.0): board_BLACK_F407ZE.md
        - BLACK F407ZG (M4 DEMO): board_BLACK_F407ZG.md
    - Nucleo-64 boards:
        - Nucleo-F030R8: board_Nucleo_F030R8.md
        - Nucleo-F103RB: board_Nucleo_F103RB.md
        - Nucleo-F303RE: board_Nucleo_F303RE.md
        - Nucleo-F401RE: board_Nucleo_F401RE.md
        - Nucleo-F411RE: board_Nucleo_F411RE.md
        - Nucleo-L053R8: board_Nucleo_L053R8.md
        - Nucleo-L152RE: board_Nucleo_L152RE.md
        - Nucleo-L476RG: board_Nucleo_L476RG.md
    - Nucleo-144 boards:
        - Nucleo-F767ZI: board_Nucleo_F767ZI.md
    - Discovery L053C8: board_DISCOVERY_L053C8.md
    - Discovery F303VC: board_DISCOVERY_F303VC.md
    - Discovery F407VG: board_DISCOVERY_F407VG.md
    - Discovery F746NG: board_DISCOVERY_F746NG.md
    - Adding a board: add_board.md
    - Testing a board: test.md
- About: about.md

